import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {getServerSession} from "next-auth";
import Logout from "./logout";
import {signIn} from "next-auth/react";
import {authOptions} from "@/lib/auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
title: "Create Next App",
       description: "Generated by create next app",
};

export default async function RootLayout({
        children,
        }: Readonly<{
children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);
    return (
            <html lang="en">
            <body className={inter.className}>
            {/* <nav>
            {!!session && <Logout /> }
            {!!session && <Link href="/profile">Profile</Link> }
            {!session && <Link href="/login">Login</Link>}</nav> */}
            {children}</body>
            </html>
           );
}
